name: Build Documentation

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  Python_Version: '3.10'

jobs:
  build_docs:
    name: Build Documentation 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Openjij Source
        run: | 
          gh release download --repo OpenJij/OpenJij --archive=tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tar 
        run: |
          find ./ -iname *.tar.gz | xargs tar -zxvf
      - name: du -a
        shell: bash
        run: du -a
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: ${{env.Python_Version}}
      - name: Python Cache Key
        shell: bash
        run: |
          echo $(which python) > /tmp/python_version.txt
      - name: Get pip cache dir
        shell: bash
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Pip-Tools 
        shell: bash
        run: |
          python -m pip install pip-tools 
          pip-compile
          pip-compile doc-requirements.in
      - name: pip cache
        uses: actions/cache@v3
        with:
           path: ${{ steps.pip-cache.outputs.dir }}
           key: ${{ runner.os }}-pip-${{ hashFiles('/tmp/python_version.txt') }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('doc-requirements.txt') }}
           restore-keys: |
              ${{ runner.os }}-pip-${{ hashFiles('/tmp/python_version.txt') }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('doc-requirements.txt') }}
              ${{ runner.os }}-pip-${{ hashFiles('/tmp/python_version.txt') }}-${{ hashFiles('requirements.txt') }}
              ${{ runner.os }}-pip-${{ hashFiles('/tmp/python_version.txt') }}
      - name: Update
        run: | 
         pip install --upgrade pip wheel setuptools 
      - name: Install Dependencies
        shell: bash
        run: |
          set -eux
          pip-sync requirements.txt doc-requirements.txt
      - name: Sphinx
        shell: bash
        run: |
          python -m sphinx-apidoc -f -o ./source/apis ./OpenJij/openjij -d 2
      - name: Make
        shell: bash
        run: |
          make html
      - name: du -a 
        shell: bash
        if: always()
        run: |
          du -a
      - name: Prepare tag
        id: prepare_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=tag_name::${TAG_NAME}"
          echo "::set-output name=deploy_tag_name::deploy-${TAG_NAME}"
      - name: Deploy
        if: ${{github.event_name == 'release'}}
        uses: peaceiris/actions-gh-pages@v3
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: public
         destination_dir: docs
         allow_empty_commit: true
         user_name: 'github-actions[bot]'
         user_email: 'github-actions[bot]@users.noreply.github.com'
         tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
         tag_message: 'Deployment ${{ steps.prepare_tag.outputs.tag_name }}'
